# Generated by Django 6.0.3 on 2026-04-05 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('QUEDA', 'Queda na Geração'), ('SUJEIRA', 'Sujeira nos Painéis'), ('DEFEITO', 'Possível Defeito'), ('SOMBRA', 'Sombreamento Detectado'), ('DEGRAD', 'Degradação Natural')], default='QUEDA', max_length=10, verbose_name='Tipo de Alerta')),
                ('descricao', models.TextField(verbose_name='Descrição do Alerta')),
                ('geracao_real_kwh', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Geração Real (kWh)')),
                ('geracao_esperada_kwh', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Geração Esperada (kWh)')),
                ('desvio_percentual', models.FloatField(help_text='Diferença percentual entre real e esperado', verbose_name='Desvio Percentual (%)')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10, verbose_name='Prioridade')),
                ('resolvido', models.BooleanField(default=False, verbose_name='Resolvido')),
                ('data_alerta', models.DateTimeField(auto_now_add=True, verbose_name='Data do Alerta')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('projeto_nome', models.CharField(blank=True, max_length=200, verbose_name='Nome do Projeto')),
                ('projeto_potencia_kwp', models.FloatField(blank=True, null=True, verbose_name='Potência do Projeto (kWp)')),
            ],
            options={
                'verbose_name': 'Alerta de Manutenção',
                'verbose_name_plural': 'Alertas de Manutenção',
                'ordering': ['-data_alerta'],
            },
        ),
        migrations.CreateModel(
            name='DadosSatelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Latitude do local (-90 a 90)', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude')),
                ('longitude', models.FloatField(help_text='Longitude do local (-180 a 180)', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
                ('irradiacao_media_anual', models.FloatField(blank=True, null=True, verbose_name='Irradiação Média Anual (kWh/m²/dia)')),
                ('dados_mensais_json', models.TextField(blank=True, default='{}', verbose_name='Dados Mensais (JSON)')),
                ('temperatura_media', models.FloatField(blank=True, null=True, verbose_name='Temperatura Média (°C)')),
                ('fonte_api', models.CharField(default='NASA POWER', max_length=100, verbose_name='Fonte da API')),
                ('data_consulta', models.DateTimeField(auto_now_add=True, verbose_name='Data da Consulta')),
            ],
            options={
                'verbose_name': 'Dado de Satélite',
                'verbose_name_plural': 'Dados de Satélite',
                'ordering': ['-data_consulta'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='core_dadoss_latitud_108b1a_idx')],
            },
        ),
    ]
